name: frost
version: 0.1.0.0
github: "githubuser/frost"
license: BSD3
author: "Ysnr Kdm"
maintainer: "euphonictech@gmail.com"
copyright: "2022 Ysnr Kdm"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/frost#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec
  - containers

library:
  source-dirs: src

executables:
  frost-exe:
    main: Main.hs
    source-dirs: src/app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frost

tests:
  frost-test:
    main: Test.hs
    source-dirs: src/test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frost
      - HUnit
      - test-framework
      - test-framework-hunit
  frost-test-functional:
    main: Test.hs
    source-dirs: src/test/functional
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frost
      - HUnit
      - test-framework
      - test-framework-hunit
  frost-test-timed:
    main: Test.hs
    source-dirs: src/test/timed
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frost
      - HUnit
      - test-framework
      - test-framework-hunit

benchmarks:
  frost-benchmark:
    main: Bench.hs
    source-dirs: src/bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - frost
      - criterion
      - HUnit
      - statistics
